// ─── Theme: Consistent with vendor-dashboard ─────────────────
export const T = {
  bg: "bg-background",
  card: "bg-card",
  accent: "hsl(var(--primary))",
  accentBg: "bg-primary",
  accentText: "text-primary",
  accentLight: "bg-primary/10",
  text: "text-foreground",
  muted: "text-muted-foreground",
  border: "border-border",
  success: "text-emerald-600 dark:text-emerald-400",
  successBg: "bg-emerald-50 dark:bg-emerald-950/30",
  successBorder: "border-emerald-200 dark:border-emerald-800",
  warning: "text-amber-600 dark:text-amber-400",
  warningBg: "bg-amber-50 dark:bg-amber-950/30",
  warningBorder: "border-amber-200 dark:border-amber-800",
  danger: "text-red-600 dark:text-red-400",
  dangerBg: "bg-red-50 dark:bg-red-950/30",
  dangerBorder: "border-red-200 dark:border-red-800",
  infoBg: "bg-blue-50 dark:bg-blue-950/30",
  infoText: "text-blue-600 dark:text-blue-400",
  infoBorder: "border-blue-200 dark:border-blue-800",
};
