// ─── Theme: Consistent with vendor-dashboard ─────────────────
export const T = {
  bg: "bg-[#faf6f1]",
  card: "bg-white",
  accent: "#c2703e",
  accentBg: "bg-[#c2703e]",
  accentText: "text-[#c2703e]",
  accentLight: "bg-[#c2703e]/10",
  text: "text-[#2d2017]",
  muted: "text-[#8a7560]",
  border: "border-[#e8dfd4]",
  success: "text-emerald-600",
  successBg: "bg-emerald-50",
  successBorder: "border-emerald-200",
  warning: "text-amber-600",
  warningBg: "bg-amber-50",
  warningBorder: "border-amber-200",
  danger: "text-red-600",
  dangerBg: "bg-red-50",
  dangerBorder: "border-red-200",
  infoBg: "bg-blue-50",
  infoText: "text-blue-600",
  infoBorder: "border-blue-200",
};
